spring:
  datasource:
    url: jdbc:mysql://localhost:3306/interview_db
    username: root
    password: sarkar   # ‚Üê change this

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8080